# Generated by Django 5.2.4 on 2025-09-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_managers_driver_phone_driver_recenttrips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('supervisor', 'Supervisor')], default='driver', max_length=20),
        ),
    ]
