# Generated by Django 5.2.4 on 2025-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
