# Generated by Django 5.2.4 on 2025-09-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_trip_polyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldlog',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eldlogs', to='backend.trip'),
        ),
    ]
