# Generated by Django 5.2.4 on 2025-09-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_eldlog_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldlog',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Submitted', max_length=16),
        ),
    ]
