# Generated by Django 5.2.4 on 2025-09-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_eldlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='backend.supervisor'),
        ),
    ]
