# Generated by Django 5.2.4 on 2025-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_driver_supervisor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['supervisor'], name='backend_app_supervi_d5e3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status'], name='backend_app_status_d5ed77_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['date'], name='backend_app_date_1cd245_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['supervisor'], name='backend_dri_supervi_54a261_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['office'], name='backend_dri_office_c0052c_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['terminal'], name='backend_dri_termina_53314f_idx'),
        ),
        migrations.AddIndex(
            model_name='eldlog',
            index=models.Index(fields=['driver'], name='backend_eld_driver__edc05a_idx'),
        ),
        migrations.AddIndex(
            model_name='eldlog',
            index=models.Index(fields=['date'], name='backend_eld_date_f62ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='eldlog',
            index=models.Index(fields=['status'], name='backend_eld_status_b2b471_idx'),
        ),
        migrations.AddIndex(
            model_name='eldlog',
            index=models.Index(fields=['trip'], name='backend_eld_trip_id_c8a4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver'], name='backend_tri_driver__3d5775_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['date'], name='backend_tri_date_010c50_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='backend_tri_status_f58866_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('trip', 'eldlog', 'status'), name='uniq_pending_trip_eldlog'),
        ),
    ]
